name: Version Bump and Merge

on:
  pull_request:
    branches:
      - 'back-end'
    types: [closed]

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Determine version bump
      id: version
      run: |
        BRANCH_NAME=$(echo ${{ github.head_ref }} | tr '[:upper:]' '[:lower:]')
        if [[ $BRANCH_NAME == "fix_"* ]]; then
          echo "bump=patch" >> $GITHUB_ENV
        elif [[ $BRANCH_NAME == "feature_"* ]]; then
          echo "bump=minor" >> $GITHUB_ENV
        elif [[ $BRANCH_NAME == "release_"* ]]; then
          echo "bump=major" >> $GITHUB_ENV
        else
          echo "Unsupported branch naming convention: $BRANCH_NAME"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Bump version and update Docker image
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    
        # Check Git status
        git status
    
        # If there are changes, either commit or discard them
        git add .
        git diff --cached --quiet || git commit -m "Committing changes before version bump"
    
        # Run npm version after ensuring a clean working directory
        npm version ${{ env.bump }}
    
        # Update Docker image version in docker-compose
        sed -i "s|image: \"rdv-app_backend:.*|image: \"rdv-app_backend:$(node -p "require('./package.json').version")\"|" docker-compose.yml
    
        # Commit and push version change and tag
        git add package.json package-lock.json docker-compose.yml
        git commit -m "Bump version to $(node -p "require('./package.json').version")"
        git push origin HEAD --follow-tags  
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    # - name: Create Git tag
    #   run: git tag -a "TAG_back-end_$(node -p "require('./package.json').version")" -m "Tagging release"

    # - name: Update Docker image version in docker-compose
    #   run: |
    #     sed -i "s|image: \"rdv-app_backend:.*|image: \"rdv-app_backend:$(node -p "require('./package.json').version")\"|" docker-compose.yml
        
    # - name: Commit and push version change and tag
    #   run: |
    #     git config user.email "actions@github.com"
    #     git config user.name "GitHub Actions"
    #     git add package.json package-lock.json docker-compose.yml
    #     git commit -m "Bump version to $(node -p "require('./package.json').version")"
    #     git push
    #     git push origin "TAG_back-end_$(node -p "require('./package.json').version")"
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
    # - name: Close Pull Request
    #   run: gh pr close -R ${{ github.repository }} -N ${{ github.event.number }}
