name: Test and Coverage

on:
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cc
          MYSQL_USER: student
          MYSQL_PASSWORD: student
        ports:
          - 3310:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: |
          result=$(npm run test:ci)
          if echo "$result" | grep -q "not met"; then
            echo "Error: Some tests failed."
            exit 1
          else
            echo "Tests passed successfully."
            echo "Continuing execution after test result check..."
            exit 0
          fi

      - name: Upload coverage to Coveralls
        run: npm run coveralls  
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

 
