name: Test and Coverage

on:
  push:
    branches:
      - 'fix_*'
      - 'feature_*'
      - 'release_*'

jobs:
  test-and-coverage:
    runs-on: ubuntu-22.04.3
    
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: rdv
          MYSQL_USER: student
          MYSQL_PASSWORD: student
        ports:
          - 3310:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up environment variables
        run: |
          echo "MYSQL_DB_HOST=localhost" >> $GITHUB_ENV
          echo "MYSQL_DB_PORT=3310" >> $GITHUB_ENV
          echo "MYSQL_DB_USER=student" >> $GITHUB_ENV
          echo "MYSQL_DB_PASSWORD=student" >> $GITHUB_ENV
          echo "MYSQL_DB_DATABASE=rdv" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Check coverage thresholds
        run: npm run check-coverage-thresholds

      - name: Upload coverage to Coveralls
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
